Homeowrk 20.04
Gev544/devops-prof-march pull request #2
Opened 2024-04-19 15:44 UTC by yesayanhaykaz

Creating VPC with all sections and launching EC2 instance with bash script.

2024-04-22 08:04 UTC, yesayanhaykaz commented
Added cleanup function for error handling block.

2024-05-11 06:21 UTC, Gev544 commented on 20-04-24/haykaz-yesayan/create_vpc.sh
there is no need to have cleanup in both scripts. 
cleanup script can be used after creation failure.

2024-05-11 06:21 UTC, Gev544 requested changes
there is no need to have cleanup in both scripts.
cleanup script can be used after creation failure.

2024-05-25 06:07 UTC, Gev544 approved these changes

2024-05-25 06:07 UTC, merged